on:
    push:
        branches:
        - newmain

permissions:
    contents: write
    pull-requests: write

name: release-please-alpha

jobs:
    release-please:
        runs-on: ubuntu-latest
        steps:
          - uses: googleapis/release-please-action@v4
            with:
              config-file: release-please-config.json
              target-branch: newmain
              
