on:
    push:
        branches:
            - newmain
permissions:
    contents: write
    pull-requests: write

name: release-please-alpha

jobs:
    release-please:
        runs-on: ubuntu-latest
        steps:
            - uses: googleapis/release-please-action@v4
              with:
                # Configuration file relative to repository root
                config-file: release-please-config.json
                # Target branch for pull requests
                target-branch: newmain